# Generated by Django 4.2.4 on 2023-08-08 11:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='images/common_images/%Y/%m/%d')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('abstractreference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cars.abstractreference')),
                ('special_offer_discount', models.IntegerField(blank=True, default=0, help_text="Vehicle incentives and rebates are programs made available by car manufacturers to encourage vehicle sales by providing consumers with cash allowances or favorable financing/lease rates. Incentives can vary by location, vehicle configuration, as well as the buyer's method of payment (cash purchase, financing, lease). Some incentives can be stacked with other incentive programs, and some have eligibility conditions that must be met to qualify. Additional incentives are sometimes targeted to customer segment groups like college graduates, military members, etc. Incentives are normally subject to change and governed by specific eligibility rules. Please see your local dealer for details on incentives that might be available to you.", null=True)),
            ],
            bases=('cars.abstractreference',),
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('abstractreference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cars.abstractreference')),
            ],
            bases=('cars.abstractreference',),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('abstractreference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cars.abstractreference')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carbrand')),
            ],
            bases=('cars.abstractreference',),
        ),
        migrations.CreateModel(
            name='CarBrandOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_text', ckeditor.fields.RichTextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(default=2023)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('robotic', 'Robotic'), ('variable', 'Variable')], max_length=255)),
                ('drivetrain', models.CharField(choices=[('fwd', 'FWD'), ('rwd', 'R  WD'), ('4wd', '4WD')], max_length=255)),
                ('fuel', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=255)),
                ('vin', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('exterior', models.CharField(max_length=255)),
                ('mileage', models.PositiveIntegerField()),
                ('interior', models.CharField(max_length=255)),
                ('consumption', models.CharField(blank=True, max_length=255, null=True)),
                ('power_reserve', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_number', models.PositiveBigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('thumbnail', models.FileField(upload_to='new_car_images/%Y/%m/%d')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
                ('car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype')),
            ],
        ),
    ]
