<template>
  <p>
    By accessing or using this website, any of its pages and/or any of the services referenced herein, you accept and agree to be bound by the Terms of Service set forth below.<br><br>
    <b>1. ARBITRATION AGREEMENT AND WAIVER OF RIGHT TO BRING COLLECTIVE ACTION.</b><br>
You and VIPMotors agree to final and binding arbitration of all Claims (as defined in the Arbitration Agreement) before the American Arbitration Association pursuant to the written Arbitration Agreement (the “Arbitration Agreement”). PLEASE READ THE ARBITRATION AGREEMENT CAREFULLY. IT AFFECTS YOUR RIGHTS, AND THOSE TO WHOM YOU PROVIDE ACCESS TO YOUR ACCOUNT. THE AGREEMENT TO ARBITRATE ALL CLAIMS IS A CONDITION OF YOUR USE OF THE VIPMotors WEBSITE AND/OR ANY OF THE SERVICES REFERENCED HEREIN.<br><br>
    <b>2. CHOICE OF LAW.</b><br>
Except as otherwise expressly provided in the VIPMotors Arbitration Agreement (which applies the Federal Arbitration Act), the relationship between you and VIPMotors are governed by the laws of the State of California without regard to its conflict/choice of law provisions.<br><br>
    <br><b>3. ACCEPTANCE OF TERMS.</b><br>
VIPMotors, Inc. (“VIPMotors,” “we,” “us,” or “our”) provides users with an online automotive information and communications platform, as well as related services that can be accessed from or through this website (collectively, “Services”). Please carefully read these Terms of Service before using the Services. By accessing or using the Services, including this website, you accept and agree to be bound by these Terms of Service (“Terms of Service”) and all applicable laws, rules, and regulations associated with your use of the Services. If you do not agree to the Terms of Service, you are not authorized to use this website or the Services. These Terms of Service also apply to any co-branded or framed version of this website.
Your use of certain materials and features of this website and/or the Services may be subject to additional terms and conditions which are incorporated herein by reference and become part of the Terms of Service. By using those materials and features, you also agree to be bound by such additional terms and conditions. Unless explicitly stated otherwise, any new features that augment or enhance the current Services shall be subject to the Terms of Service.
This website is controlled and operated by VIPMotors from its offices within the United States. VIPMotors makes no representation that information or materials available on this website are appropriate or available for use in other locations, and access to this website from territories where its contents are illegal is prohibited. Those who choose to access this website from other locations do so at their own initiative and are responsible for compliance with applicable local laws.
<br><br><b>4. USER CONDUCT</b><br>
You are authorized by VIPMotors to access and use the Services, including the information on this website, solely for your personal, non-commercial use provided that you are at least 18 years of age. The information and materials displayed on this website may not otherwise be copied, transmitted, displayed, distributed, downloaded, licensed, modified, published, posted, reproduced, used, sold, transmitted, used to create a derivative work, or otherwise used for commercial or public purposes without VIPMotors’s express prior written consent. Any use of data mining, robots or similar data gathering or extraction tools or processes in connection with this website, and any reproduction or circumvention of the navigational structure or presentation of this website or its content, is strictly prohibited. You agree not to use the Services, including this website, for any unlawful purpose.
In order to access certain features of this website you may be required to register. You are responsible for maintaining the confidentiality of your password and account and are fully responsible for all activities that occur under your password or account. You agree to immediately notify VIPMotors in writing of any unauthorized use of your password or account or any other breach of security, and ensure that you exit from your account at the end of each session. VIPMotors is not liable for any loss or damage arising from your failure to comply with this section. You agree not to modify the Services or use modified versions of the Services (except if modified by VIPMotors), including for the purpose of obtaining unauthorized access to the Services. You agree not to access the Services by any means other than through the interface that is provided by VIPMotors for use in accessing the Services.
<br><br><b>5. TELEPHONIC COMMUNICATIONS WITH VIPMotors, VIPMotors CERTIFIED DEALERS, VIPMotors PARTICIPATING LENDERS AND THIRD PARTY PARTNERS</b><br>
You acknowledge that telephone calls to or from VIPMotors, VIPMotors Certified Dealers, VIPMotors Participating Lenders, and/or third party partners (“VIPMotors Parties”) may be monitored and recorded and you agree to such monitoring and recording. If you select the “text only” option when submitting your telephone number to a VIPMotors Certified Dealer, your number will be hidden from the dealer. VIPMotors will have access to your text communications with the dealer using our services to help resolve any disputes, enforce rules to respect your privacy, and better tailor our services to you.
You verify that any contact information provided to VIPMotors Parties, including, but not limited to, your name, mailing address, email address, your residential telephone number, and/or your mobile telephone number, is true and accurate. You verify that you are the current subscriber or owner of any telephone number that you provide. You are strictly prohibited from providing a phone number that is not your own. If we discover that any information provided in connection with your account registration is false or inaccurate, we may suspend or terminate your account at any time. Should any of your contact information change, including ownership of your telephone number(s), you agree to immediately notify us by texting STOP to any text message or calling us, in accordance with the instructions below.
You agree to indemnify, defend and hold the VIPMotors Parties harmless from and against any and all claims, losses, liability, costs and expenses (including reasonable attorneys’ fees), including, but not limited to, claims under the Federal Telephone Consumer Protection Act or its state law equivalent, and including claims arising from your voluntary provision of contact information (including a telephone number) that is not your own, your failure to notify us of any changes to your contact information, including telephone number, and/or from your violation of any federal, state or local law, regulation or ordinance. We shall have the exclusive right to choose counsel, at your expense, to defend any such claims.
You acknowledge that by voluntarily providing your telephone number(s) to VIPMotors Parties, you expressly agree to receive prerecorded voice messages and/or autodialed calls or text messages related to pricing and offers, vehicle financing and loans, your account, any transaction, and/or your relationship with VIPMotors Parties. This does not mean that all calls or text messages to you will be sent through automated means. You also agree to be contacted at email and mailing addresses provided by you. Consent to receive automated marketing calls/texts is not a condition of any purchase, lease, financing or loan. Calls or text messages may be sent by VIPMotors Parties even if your telephone number is registered on any state or federal Do Not Call list. You acknowledge that we may add to or withdraw dealers, lenders, or third party partners from our participating partner list at any time, and you consent to be contacted, as explained above, by these dealers, lenders or third party partners notwithstanding the date of the start of your relationship with VIPMotors. Your consent to be contacted applies to participating dealers, lenders or third party partners that may have existed at the start of your relationship with VIPMotors and that may thereafter be added to VIPMotors’s participating partner list. You acknowledge that you may incur a charge for calls or text messages by your telephone carrier and that VIPMotors Parties are not responsible for these charges.
Your consent to receive automated calls and texts is completely voluntary. You may opt-out of automated calls or text messages at any time. To opt-out of text messages, reply STOP to any text message you receive or follow other opt-out instructions included with the text message. You acknowledge and agree that you may receive a text message confirming your opt-out. We may use different shortcodes or phone numbers for different purposes to better serve you. Texting STOP to one shortcode or phone number does not effectuate a stop request for all shortcodes or phone numbers to which you are subscribed. If you would like to stop messages from multiple shortcodes or phone numbers, text STOP to each shortcode or each phone number to which you would like to unsubscribe.
To opt-out of automated telephone calls from VIPMotors (but not text messages), call (888)-VIPMotors. It is your sole responsibility to notify us if you no longer want to receive automated calls or text messages. To opt-out of receiving automated telephone calls or texts from participating dealers, lenders, or third party partners, please contact the dealer, lender or third party partner directly. We are not responsible for unwanted contact from third parties. You waive any rights to bring claims for unauthorized or undesired calls or text messages by failing to opt out immediately or by failing to follow these instructions. Please allow up to thirty (30) days to process any opt-out request. Please note that if you opt out of automated calls, VIPMotors Parties reserve their right to make non-automated calls to you relating to your account, any transaction, or their relationship with you. Your obligations under this Section shall survive termination of these Terms of Service.
You are responsible for obtaining and maintaining all telephone devices and other equipment and software, and all internet service provider, mobile service, and other services needed to receive calls and text messages. Text messaging may only be available with select carriers with compatible handsets.
    <br><br><b>6. PRIVACY</b><br>
VIPMotors is committed to respecting your privacy and protecting your personally identifiable information. Upon your request, VIPMotors shares the information you enter on this website with participating dealers and/or buyers in order to provide you with the information you requested, and with other service providers associated with the Services. VIPMotors account data and certain other information about you and that you enter and/or we collect through your use of this website are subject to the VIPMotors Privacy Policy. You understand that through your use of the Services, including this website, you consent to the collection and use (as set forth in the VIPMotors Privacy Policy) of this information. Please review our Privacy Policy for further information on our data collection and use practices.
<br><br><b>7. SERVICES</b><br>
All information provided on this website is for informational purposes only. Information displayed through the Services related to any virtual vehicle you may configure, such as dealer cost, factory invoice, market average, MSRP, VIPMotors Average, VIPMotors Estimate, or Estimated Savings off MSRP, either reflects or is based on available data relevant to your virtual vehicle and does not reflect a dealer's price for an actual vehicle consistent with your preferences. Any savings information that you may receive from a selling dealer or user, such as Estimated Member Savings, Estimated Member Price, Guaranteed Savings, Member Savings, Certified Dealer MSRP Discount, Total Dealer Fees and Accessories, Total Before Tax, or Estimated VIPMotors Dealer Price is provided directly to you by the selling dealer or user, and is not provided by VIPMotors. Any incentive offer that you may receive from vehicle manufacturers through your use of the Services is provided directly to you by that vehicle manufacturer, and is not provided by VIPMotors. The terms and conditions of these incentive offers are determined by the applicable vehicle manufacturer, and not by VIPMotors. VIPMotors also provides you with valuable access to links to third party sites where you can obtain financing and insurance. Information you may receive from third parties is provided directly to you by that financial institution or insurance provider, and is not provided by VIPMotors.
Neither the accuracy of information provided on this website, nor the availability, quality, or safety of vehicles, or any financing of or insurance relevant to those vehicles, is guaranteed or controlled by VIPMotors, and VIPMotors assumes no responsibility for the foregoing. You agree that any reliance on the information on this website is at your own risk. Any discrepancies or mistakes made regarding vehicle availability, condition, pricing, financing, insurance and the like are not the responsibility of VIPMotors and should be directed to the dealer or appropriate third party vendor. For example, vehicle history reports and certain vehicle condition information has been provided by AutoCheck. VIPMotors is not responsible for any errors, discrepancies, or mistakes in reports or information from that unaffiliated third party. You are encouraged to thoroughly review any documents you are asked to sign at the time of purchase or lease of a vehicle or of other products or services. We do invite you to bring to our attention any material on our website that you believe to be inaccurate; please forward a copy of such material and your reasons for your belief to feedback@VIPMotors.com.
By using the Services, you acknowledge and agree that participating dealers may not have in inventory a new vehicle that exactly matches any virtual vehicle you may configure on the website, and certain models or configurations may not be available. Your dealer will confirm vehicle availability, including available options and colors, from actual inventory. Each dealer sets and controls its own pricing. You may negotiate the purchase price directly with the dealer, and VIPMotors plays no role in that negotiation. The savings information communicated directly to you by a selling dealer for a vehicle consistent with the preferences expressed in any virtual vehicle you may configure may change if the actual in-stock vehicle that you choose to buy differs from the configuration of your virtual vehicle. Used vehicles are subject to prior sale.
For the avoidance of doubt, VIPMotors is solely a research and communications platform. VIPMotors is not a vehicle seller, dealer, broker or agent for vehicle sellers or dealers, nor a provider of, or broker or agent for, other automotive-related products or services offered by third parties. VIPMotors receives a fee from the participating dealers or third-party service providers in connection with the Services.
<br><br><b>8. NO COMMERCIAL USE OF SERVICES</b><br>
You agree not to reproduce, duplicate, copy, sell, trade, resell or exploit for any commercial purposes, any portion or use of, or access to, the Services.
<br><br><b>9. RIGHT TO DENY ACCESS AND TO MODIFY THE SERVICES</b><br>
VIPMotors reserves the right to deny use of, or access to, the Services to you and/or anyone for any or no reason. VIPMotors also reserves the right at any time and from time-to-time to modify or discontinue, temporarily or permanently, the Services (or any part thereof) with or without notice. You agree that VIPMotors shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Services (or any part thereof).
<br><br><b>10. INDEMNIFICATION</b><br>
You will indemnify, defend and hold harmless VIPMotors and its subsidiaries, affiliates, partners, officers, directors, employees, and agents (collectively, “VIPMotors Entities”) from all claims, whether actual or alleged (collectively, “Indemnified Claims”), that arise out of or in connection with a breach of these Terms of Service, use of the Services, including any content you submit, post, transmit, modify or otherwise make available through the Services, and/or any violation of law and/or the rights of any third party. You are solely responsible for defending any Indemnified Claim against a VIPMotors Entity, subject to such VIPMotors Entity’s right to participate with counsel of its own choosing, at its own expense, and for payment of all judgments, settlements, damages, losses, liabilities, costs, and expenses, including reasonable attorneys’ fees, resulting from all Indemnified Claims against a VIPMotors Entity, provided that you will not agree to any settlement that imposes any obligation or liability on a VIPMotors Entity without its prior express written consent.
<br><br><b>11. DISCLAIMER OF WARRANTIES</b><br>
THE SERVICES, INCLUDING ALL INFORMATION AND CONTENT ON OR OTHERWISE RELATED IN ANY WAY TO THE SERVICES, THIS WEBSITE OR ANY THIRD-PARTY WEBSITE, PRODUCT, OR SERVICE LINKED TO OR FROM THIS WEBSITE, ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TIMELINESS, AND NONINFRINGEMENT. IN ADDITION, VIPMotors DOES NOT WARRANT AGAINST DEFECTS IN ANY VEHICLE, AND DOES NOT MAKE ANY WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING REPRESENTATIONS, PROMISES, OR STATEMENTS AS TO THE CONDITION, FITNESS, OR MERCHANTABILITY OF ANY VEHICLE OR SERVICE. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM VIPMotors OR THROUGH OR LINKED FROM THE SERVICES SHALL CREATE ANY WARRANTY EXPRESS OR IMPLIED. VIPMotors is not responsible for making repairs to any vehicle. If you have complaints or concerns about defects or repairs, please contact the dealer, seller, or manufacturer directly.
<br><br><b>12. LIMITATION OF LIABILITY; WAIVER</b><br>
IN NO EVENT SHALL THE VIPMotors ENTITIES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE OF DATA, INFORMATION, AND/OR CONTENT, OR OTHER INTANGIBLE LOSSES ARISING OUT OF, OR IN CONNECTION WITH THE SERVICES, INCLUDING ALL INFORMATION AND CONTENT ON OR OTHERWISE RELATED IN ANY WAY TO THIS WEBSITE OR ANY THIRD-PARTY WEBSITE, PRODUCT, OR SERVICE LINKED TO OR FROM THIS WEBSITE, OR ANY VEHICLE REFERENCED THEREIN. WITHOUT LIMITING THE FOREGOING, ANY INFORMATION AND CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICES IS ACCESSED AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR AND HEREBY WAIVE ANY AND ALL CLAIMS AND CAUSES OF ACTION WITH RESPECT TO ANY DAMAGE TO YOUR COMPUTER SYSTEM, INTERNET ACCESS, DOWNLOAD OR DISPLAY DEVICE, OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH INFORMATION AND CONTENT. YOUR SOLE AND EXCLUSIVE REMEDY FOR DISSATISFACTION WITH ANY SERVICE AND/OR THIS WEBSITE IS TO STOP USING THE SERVICE AND/OR WEBSITE.
YOU HEREBY IRREVOCABLY WAIVE ANY CLAIM (WHETHER FOR INJURY, ILLNESS, DAMAGE, LIABILITY AND/OR COST) AGAINST THE VIPMotors ENTITIES ARISING OUT OF YOUR USE OF OR INABILITY TO USE, OR IN CONNECTION WITH, THE SERVICES, INCLUDING ANY INFORMATION AND CONTENT ON THIS WEBSITE OR ANY THIRD-PARTY WEBSITE, PRODUCT, OR SERVICE LINKED TO OR FROM THIS WEBSITE, INCLUDING ANY CONTENT YOU PROVIDE TO THIRD PARTIES (INCLUDING PERSONALLY IDENTIFIABLE INFORMATION).
<br><br><b>13. EXCLUSIONS AND LIMITATIONS</b><br>
SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN IMPLIED WARRANTIES, OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE EXCLUSIONS AND LIMITATIONS MAY NOT APPLY TO YOU.
<br><br><b>14. NOTICE</b><br>
VIPMotors may provide you with notices by email, regular mail, SMS, MMS, text message, postings on the Services/website, or other reasonable means now known or hereafter developed. You acknowledge and agree that VIPMotors will have no liability associated with or arising from your failure to maintain and supply VIPMotors with accurate contact information about yourself, including your failure to receive important information and updates about the Services or this website.
<br><br><b>15. TRADEMARK INFORMATION AND INTELLECTUAL PROPERTY</b><br>
You agree that all of VIPMotors’s trademarks, trade names, service marks, logos, brand features, and product and Service names are trademarks and the property of VIPMotors, and that you will not display or use any of the foregoing without VIPMotors's prior written approval in each instance.
You agree that the Services contain proprietary information protected by applicable intellectual property and other laws in favor of VIPMotors. You further agree that content and information presented to you through the Services is protected by copyrights, trademarks, service marks, patents and/or other proprietary rights and laws.
<br><br><b>16. COPYRIGHT OR INTELLECTUAL PROPERTY COMPLAINTS</b><br>
VIPMotors respects the intellectual property of others. If you believe that your work has been copied in a way that constitutes copyright infringement, or your intellectual property rights have been violated, please provide us with the following information:
a physical signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property right;
a description of the copyrighted work or other intellectual property that you claim has been infringed or violated;
a description of where the material that you claim is infringing is located on our website;
your address, telephone number, and email address;
a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright or intellectual property owner, its agent, or the law;
a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner's behalf.
<br><br><b>17. GENERAL INFORMATION</b><br>
These Terms of Service may be amended from time to time without notice in VIPMotors’s sole discretion. Any changes to the Terms of Service will be effective immediately upon the posting of the revised Terms of Service on this website. The Terms of Service, including any agreements and terms incorporated by reference herein, constitute the entire agreement between you and VIPMotors and govern your use of the Services, including this website, and supersede any prior version of these Terms of Service between you and VIPMotors with respect to the Services. You agree that no agency relationship is created between you and VIPMotors as a result of these Terms of Service or your access to and/or use of the Services. The failure of VIPMotors to exercise or enforce any right or provision of the Terms of Service shall not constitute a waiver of such right or provision. If any provision of the Terms of Service is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of the Terms of Service remain in full force and effect. You agree that, except as otherwise expressly provided in these Terms of Service, there shall be no third-party beneficiaries to these Terms of Service. The headings in these Terms of Service are for convenience only and have no legal or contractual effect. As used in these Terms of Service, the word “including” is a term of enlargement meaning “including without limitation” and does not denote exclusivity, and the words “will,” “shall,” and “must” are deemed to be equivalent and denote a mandatory obligation or prohibition, as applicable. All definitions apply both to their singular and plural forms, as the context may require. Please report any violations of the Terms of Service to violations@VIPMotors.com. Questions regarding these Terms of Service should be sent to legal@VIPMotors.com.
THE VIPMotors ENTITIES DO NOT MAKE ANY REPRESENTATION OR WARRANTY THAT YOU WILL SELL YOUR VEHICLE, OBTAIN AN ACCEPTABLE PRICE FOR YOUR VEHICLE, RECEIVE LEGITIMATE INQUIRIES OR SOLICITATIONS FROM QUALIFIED BUYERS, OR RECEIVE ANY INQUIRIES REGARDING YOUR VEHICLE FOR SALE.
<br><br><b>18. ADDITIONAL TERMS FOR THE “SELL YOUR CAR” AND TRADE</b><br>
VIPMotors offers additional services whereby you may request (i) conditional offers to purchase your used motor vehicle (excluding certain types of vehicles) (each offer, a “True Cash Offer”) using the “Sell Your Car” service, and/or (ii) an estimated trade-in value for your used motor vehicle (excluding certain types of vehicles) (each estimate, a “True Cash Estimate”) using the Trade service. If you use or participate in these services, the following additional terms apply:
In order to request a True Cash Offer or True Cash Estimate, you must have possession of the actual vehicle, with the ability to transfer valid title as set forth herein. You are required to provide certain identifying and contact information, which must accurately identify yourself so dealers can communicate directly with you. By using these services, you represent, warrant, and covenant that you are not: (i) a motor vehicle dealer or (ii) listing a vehicle for sale in your capacity as an owner, employee, or representative of a motor vehicle dealer. For clarity, if you are a motor vehicle dealer, you may not use these services to obtain a True Cash Offer or True Cash Estimate on behalf of a customer.
True Cash Offers and True Cash Estimates are not available in all areas, and not all vehicles are eligible. These services may not be used to sell or to trade-in certain categories of vehicles, including commercial vehicles; vehicles with a government, police, fire or livery history; motorcycles; recreational vehicles; reconstructed or salvage vehicles; vehicles without a valid VIN; “grey market” vehicles; vehicles older than seventeen (17) model years; vehicles with altered drivelines or bodies or illegal or non-functioning emissions equipment; flood, hail or fire damaged vehicles; vehicles with substantial mechanical or electrical damage; vehicles registered at an auto auction or offered for sale on a wholesale website within forty five (45) days prior to submitting your request; vehicles that are valued at less than $1,000; and any other category of vehicle that we, in our sole discretion, believe may adversely impact the operation of these services (each, a “Restricted Vehicle”).
By requesting a True Cash Offer or True Cash Estimate, you agree that VIPMotors, its service providers, Participating Dealers, and/or affinity partners may use the personal contact information you provided, including your telephone number and email address, to communicate with you about the products and services that may be of interest to you. By requesting a True Cash Offer or True Cash Estimate, you agree to use the email address or any other contact information of the Participating Dealer(s) only for purposes of communicating with them about the potential sale of that vehicle.
“Sell Your Car” service
Through VIPMotors’s “Sell Your Car” service, upon providing the requisite information, you can request conditional offers from dealers to purchase your used motor vehicle, known as True Cash Offers. All True Cash Offers are subject to inspection and verification of the vehicle by, or on behalf of, the purchasing dealer, as well as the terms of, and your full compliance with, these Terms of Service and any other applicable terms. A participating dealer that may make a True Cash Offer is referred to in these additional terms as a “Participating Dealer.” In certain situations, however, you may instead receive a True Cash Offer from VIPMotors Wholesale Solutions, Inc. (“TCWS”), in which case TCWS will also qualify as a “Participating Dealer” for purposes of these additional terms.
The “Sell Your Car” service enables Participating Dealers to obtain information about vehicles for which True Cash Offers have been requested and, if applicable, to contact a seller to make a True Cash Offer. We are not a party to, and do not otherwise guarantee the terms of, any True Cash Offer or any transaction resulting therefrom. You alone are responsible for any transaction you engage in resulting from a True Cash Offer from a Participating Dealer. Although Participating Dealers have agreed to abide by certain customer service standards, we are not responsible for any potential fraud or other misconduct by a Participating Dealer in connection with the “Sell Your Car” service. As a seller, you should exercise caution and good judgment when completing any transaction, including those involving this service.
Vehicles with a True Cash Offer value greater than $75,000 may not be accepted by every Participating Dealer and may require an additional inspection. If you solicit True Cash Offers for any Restricted Vehicle using the “Sell Your Car” service, you may not receive a True Cash Offer for such vehicle and, in the event that you do receive a True Cash Offer for such vehicle, you acknowledge and agree that such True Cash Offer may be invalidated and that no Participating Dealer is required to purchase such vehicle from you.
You acknowledge that if you provide any false, incomplete, or inaccurate information, including vehicle information or personal contact information, your True Cash Offer may be invalidated by the Participating Dealer.
Before submitting a request to receive a True Cash Offer from Participating Dealers, you may be able to view an estimated value associated with your vehicle. For the avoidance of doubt, any estimated value shown during this process is for informational purposes only and does not constitute, and should not be construed as, a True Cash Offer or otherwise as an offer or conditional offer by VIPMotors, a dealer, or any third party to purchase your used motor vehicle.
Although a Participating Dealer is not obligated to purchase your vehicle for any price other than the amount of your True Cash Offer (subject to your satisfaction of the requirements herein), you can try to negotiate a more favorable price for your vehicle and, of course, you are always free to sell or trade in your vehicle outside of the VIPMotors platform. The sale price that you could receive for your vehicle in the open market or from another source may be higher than the amount of the True Cash Offer you receive.
To receive a True Cash Offer from a Participating Dealer: (1) your vehicle must be located in a market in which the “Sell Your Car” service is offered and registered in the same state as the location of the applicable Participating Dealer, unless the applicable Participating Dealer is TCWS; (2) you must be the registered owner of the vehicle; (3) you must possess a valid driver’s license or other form of valid government-issued photo ID; (4) you must provide accurate, complete, and truthful personal contact information and responses to all questions included in the online questionnaire, including those relating to the description and condition of your vehicle; and (5) you must deliver your vehicle, with a valid registration and either clear and unencumbered title in your name or complete documentation regarding any lease obligations or liens on your vehicle (including, for example, contact information for your lender or leasing company, relevant account information and the current loan payoff amount or lease early termination fee for your vehicle), within 72 hours of the issuance of your True Cash Offer, to the Participating Dealer, or its designated location, for inspection by, or on behalf of, the Participating Dealer.
You are responsible for the information contained in the vehicle questionnaire, the content of all communications you transmit through the “Sell Your Car” service, and any other information you provide. We may perform random or selective quality assurance tests to confirm that individuals who request a True Cash Offer are not automobile dealers and are prepared to sell such vehicles through the service. By using the “Sell Your Car” service, you agree to cooperate in these quality assurance tests. If the tests reveal, or we otherwise learn, that a seller is violating these Terms of Service or engaging in other unfair or deceptive practices, VIPMotors may, in its sole discretion, deny that seller use of the “Sell Your Car” service or any other VIPMotors services.
Following your delivery of the applicable vehicle to the designated location, your Participating Dealer or its third-party designee will conduct a mandatory vehicle inspection free of charge to confirm the vehicle description and condition information that you provided as part of your request for a True Cash Offer. This confirmation inspection may include a road test, a mechanical inspection, a review of vehicle history reports and disclosure statements regarding flood, salvage, and/or odometer discrepancies (including rollbacks), and any other reasonable tests and/or inspections that the Participating Dealer deems necessary or advisable. In the event that the inspection reveals misrepresentations and/or inconsistencies in the vehicle condition identified by you, the Participating Dealer may (1) refuse to purchase the vehicle or (2) provide a revised True Cash Offer to you based on the actual condition of the vehicle as determined through the inspection (for clarity, such revised True Cash Offer shall invalidate and replace any prior True Cash Offers created prior to the inspection). You acknowledge and agree that we have no involvement in, or liability in connection with, the Participating Dealer or its third-party designee’s inspection of your vehicle.
Upon the satisfactory inspection of your vehicle by or on behalf of the Participating Dealer, and subject to any payments necessary to clear title as set forth below, the Participating Dealer will make a payment to you by check or ACH transfer in the amount of the valid True Cash Offer as reduced by such payments as may be required to secure the release of all applicable liens and lease obligations and the receipt of a clear and unencumbered vehicle title. The Participating Dealer will have sole discretion to decide whether payments will be available via check, ACH, or both. All payments will be made payable to the vehicle owner(s) named on the vehicle title.
If you have negative equity in your vehicle (i.e., your outstanding loan balance or lease payment obligation exceeds the amount of your True Cash Offer), you will be responsible for paying the difference between the True Cash Offer price and the amount needed to clear the title to your vehicle by certified check or other form of payment acceptable to the Participating Dealer before your transaction can be completed. If you have positive equity in your vehicle, the Participating Dealer will issue you a check for the difference between the amount needed to clear the title to your vehicle and the True Cash Offer price. The Participating Dealer will assist you with processing of the paperwork and payments necessary to settle your loan or lease obligations and to obtain a clear title to your vehicle. The process of Participating Dealer issuing you a check in connection with your positive equity in your vehicle typically takes 10 to 14 days following delivery of a vehicle to a Participating Dealer, but could take longer in some circumstances.
Trade service
Through VIPMotors’s Trade service, upon providing the requisite information, you can request that Participating Dealers present an estimated trade-in value for your used motor vehicle, known as a True Cash Estimate. Each True Cash Estimate is for informational purposes only and does not constitute, and should not be construed as, a True Cash Offer or otherwise as an offer or conditional offer by VIPMotors, a dealer, or any third party to purchase your used motor vehicle.
You can try to negotiate a more favorable trade-in value for your vehicle and, of course, you are always free to sell or trade in your vehicle outside of the VIPMotors platform. The sale price or trade-in value that you could receive for your vehicle in the open market or from another source may be higher than the amount of the True Cash Estimate you receive.
The Trade service enables Participating Dealers to obtain information about vehicles for which True Cash Estimates have been requested and, if applicable, to present a True Cash Estimate. We are not a party to any True Cash Estimate or any potential related transaction that may eventually result therefrom. Although Participating Dealers have agreed to abide by certain customer service standards, we are not responsible for any potential fraud or other misconduct by a Participating Dealer in connection with the Trade service, and you should exercise caution and good judgment when completing any transaction, including those relating to this service.
VIPMotors DOES NOT MAKE ANY REPRESENTATION OR WARRANTY THAT YOU WILL BE ABLE TO SELL OR TRADE YOUR VEHICLE, OBTAIN AN ACCEPTABLE PRICE FOR YOUR VEHICLE, RECEIVE ANY INQUIRIES OR SOLICITATIONS FROM POTENTIAL PARTICIPATING DEALERS, OR RECEIVE ANY TRUE CASH ESTIMATE RELATING TO, OR TRUE CASH OFFER FOR, YOUR VEHICLE. IN THE EVENT THAT ANY CLAIMS OR DISPUTES ARISE OUT OF AN ACTUAL OR POTENTIAL TRANSACTION FOR YOUR VEHICLE, YOU AGREE TO LOOK SOLELY TO THE PARTICIPATING DEALER FOR YOUR REMEDY AND NOT TO VIPMotors, ITS PARTNERS, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR AFFILIATES (except in cases where TCWS was the applicable Participating Dealer).
<br><br><b>19. ADDITIONAL TERMS FOR PRE-QUALIFIED AUTO FINANCING WITH PARTICIPATING LENDERS</b><br>
Prior to visiting a participating dealer, you may submit a request to a participating lender listed below to see if you pre-qualify for auto financing with no impact to your credit score. Eligibility for pre-qualification offers from participating lenders is determined by the participating lender based on the information you submitted. VIPMotors does not play a role in that determination. Pre-qualified auto financing terms are not guaranteed and subject to change based on the lender’s evaluation of your credit application submitted at the dealer and any required documents. You are encouraged to review the lender’s website for additional information about the pre-qualification process.
Participating lenders provide financing for vehicles from participating dealers. Participating dealers are subject to change. You are encouraged to verify the accuracy of any third party information on your own.
  </p>
</template>

<style scoped>
p {
  font-size: 18px;
}
</style>
<script setup>
</script>